FROM steadylearner/ubuntu_node
WORKDIR /app
COPY . /app
# Test with it first
EXPOSE 8000
CMD ["yarn", "serve"]
 
# Use it before you develop it to AWS or other services
# EXPOSE 80
# CMD ["yarn", "build"]

# EXPOSE 80
# CMD ["yarn", "build"]

